// Generated by CoffeeScript 1.3.3
(function() {
  var EightBallPlayer;

  EightBallPlayer = function(name, rank, number, teamNumber) {
    this.Name = name;
    this.Rank = rank;
    this.Number = number;
    this.TeamNumber = teamNumber;
    this.GamesWon = 0;
    this.Safeties = 0;
    this.CurrentlyUp = false;
    this.EightOnSnaps = 0;
    this.BreakAndRuns = 0;
    this.TimeoutsAllowed = new EightBallRanks().getTimeouts(rank);
    this.GamesNeededToWin = 0;
    this.IsCaptain = false;
    this.getGamesNeededToWin = function() {
      return this.GamesNeededToWin.toString();
    };
    this.resetPlayerRankStats = function() {
      return this.TimeoutsAllowed = new EightBallRanks().getTimeouts(this.Rank);
    };
    this.addOneToGamesWon = function() {
      return this.GamesWon += 1;
    };
    this.addOneToSafeties = function() {
      return this.Safeties += 1;
    };
    this.hasWon = function() {
      return this.Score >= this.BallCount;
    };
    this.addOneToEightOnSnaps = function() {
      return this.EightOnSnaps += 1;
    };
    this.addOneToBreakAndRuns = function() {
      return this.BreakAndRuns += 1;
    };
    this.getRemainingBallCount = function() {
      return (this.BallCount - this.Score).toString();
    };
    this.getFirstNameWithInitials = function() {
      var nameToReturn, spaceIndex;
      spaceIndex = this.Name.indexOf(" ");
      if (spaceIndex === -1) {
        return this.Name;
      }
      nameToReturn = this.Name.substr(0, spaceIndex);
      return nameToReturn + " " + this.Name[spaceIndex + 1] + ".";
    };
    this.getSafeties = function() {
      return this.Safeties.toString();
    };
    this.getGamesWon = function() {
      return this.GamesWon.toString();
    };
    this.getRatioScore = function() {
      return this.Score / this.BallCount;
    };
    this.getEightOnSnaps = function() {
      return this.EightOnSnaps.toString();
    };
    this.getBreakAndRuns = function() {
      return this.BreakAndRuns.toString();
    };
    this.toJSON = function() {
      return {
        Name: this.Name,
        Rank: this.Rank,
        GamesNeededToWin: this.GamesNeededToWin,
        Number: this.Number,
        TeamNumber: this.TeamNumber,
        GamesWon: this.GamesWon,
        Safeties: this.Safeties,
        EightOnSnaps: this.EightOnSnaps,
        BreakAndRuns: this.BreakAndRuns,
        CurrentlyUp: this.CurrentlyUp
      };
    };
    return this.fromJSON = function(playerJSON) {
      this.Name = playerJSON.Name;
      this.Rank = playerJSON.Rank;
      this.Number = playerJSON.Number;
      this.TeamNumber = playerJSON.TeamNumber;
      this.GamesWon = playerJSON.GamesWon;
      this.Safeties = playerJSON.Safeties;
      this.EightOnSnaps = playerJSON.EightOnSnaps;
      this.BreakAndRuns = playerJSON.BreakAndRuns;
      this.CurrentlyUp = playerJSON.CurrentlyUp;
      return this.resetPlayerRankStats();
    };
  };

}).call(this);
