// Generated by CoffeeScript 1.3.1
(function() {
  var EightBall,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  EightBall = (function(_super) {

    __extends(EightBall, _super);

    EightBall.name = 'EightBall';

    function EightBall() {
      return EightBall.__super__.constructor.apply(this, arguments);
    }

    EightBall.prototype.defaults = {
      name: null,
      rank: null,
      number: null,
      team_number: null,
      games_won: 0,
      safeties: 0,
      currently_up: false,
      eight_on_snaps: 0,
      break_and_runs: 0,
      timeouts_allowed: null,
      games_needed_to_win: 0,
      is_captain: false
    };

    EightBall.prototype.initialize = function(name, rank, number, teamNumber) {
      this.name = name != null;
      this.rank = rank != null;
      this.number = number != null;
      this.team_number = teamNumber != null;
      return this.timeouts_allowed = $CS.Models.Rank.EightBall().getTimeouts(rank != null);
    };

    EightBall.prototype.getGamesNeededToWin = function() {
      return this.games_needed_to_win.toString();
    };

    EightBall.prototype.getRemainingBallCount = function() {
      return (this.ball_count - this.score).toString();
    };

    EightBall.prototype.getFirstNameWithInitials = function() {
      var nameToReturn, spaceIndex;
      spaceIndex = this.name.indexOf(" ");
      if (spaceIndex === -1) {
        return this.name;
      }
      nameToReturn = this.name.substr(0, spaceIndex);
      return nameToReturn + " " + this.name[spaceIndex + 1] + ".";
    };

    EightBall.prototype.getSafeties = function() {
      return this.safeties.toString();
    };

    EightBall.prototype.getGamesWon = function() {
      return this.games_won.toString();
    };

    EightBall.prototype.getRatioScore = function() {
      return this.score / this.ball_count;
    };

    EightBall.prototype.getEightOnSnaps = function() {
      return this.eight_on_snaps.toString();
    };

    EightBall.prototype.getBreakAndRuns = function() {
      return this.break_and_runs.toString();
    };

    EightBall.prototype.resetPlayerRankStats = function() {
      return this.timeouts_allowed = $CS.Models.Rank.EightBall().getTimeouts(this.rank);
    };

    EightBall.prototype.addOneToGamesWon = function() {
      return this.games_won += 1;
    };

    EightBall.prototype.addOneToSafeties = function() {
      return this.safeties += 1;
    };

    EightBall.prototype.hasWon = function() {
      return this.score >= this.ball_count;
    };

    EightBall.prototype.addOneToEightOnSnaps = function() {
      return this.eight_on_snaps += 1;
    };

    EightBall.prototype.addOneToBreakAndRuns = function() {
      return this.break_and_runs += 1;
    };

    EightBall.prototype.toJSON = function() {
      return {
        name: this.name,
        rank: this.rank,
        games_needed_to_win: this.games_needed_to_win,
        number: this.number,
        team_number: this.team_number,
        games_won: this.games_won,
        safeties: this.safeties,
        eight_on_snaps: this.eight_on_snaps,
        break_and_runs: this.break_and_runs,
        currently_up: this.currently_up
      };
    };

    EightBall.prototype.fromJSON = function(playerJSON) {
      this.name = playerJSON.name;
      this.tank = playerJSON.rank;
      this.number = playerJSON.number;
      this.team_number = playerJSON.team_number;
      this.games_won = playerJSON.games_won;
      this.safeties = playerJSON.safeties;
      this.eight_on_snaps = playerJSON.eight_on_snaps;
      this.break_and_runs = playerJSON.break_and_runs;
      this.currently_up = playerJSON.currently_up;
      return this.resetPlayerRankStats();
    };

    return EightBall;

  })($CS.Models.Player);

  $CS.Models.Player.EightBall = EightBall;

}).call(this);
