// Generated by CoffeeScript 1.3.1
(function() {
  var getScoreRatio;

  getScoreRatio = function(playerScore, playerBallCount) {
    return playerScore / playerBallCount;
  };

  Array.prototype.exists = function(search) {
    var i;
    i = 0;
    while (i < this.length) {
      if (this[i] === search) {
        return true;
      }
      i++;
    }
    return false;
  };

  root.getPlatformWidth = function() {
    return Ti.Platform.displayCaps.platformWidth;
  };

  root.getPlatformHeight = function() {
    return Ti.Platform.displayCaps.platformHeight - 22;
  };

}).call(this);
