// Generated by CoffeeScript 1.3.1
(function() {
  var GenericWindow;

  GenericWindow = (function() {

    GenericWindow.name = 'GenericWindow';

    function GenericWindow(theTitle, theText) {
      var label, self;
      self = this;
      this.custom1 = "Default Value";
      this.win = Ti.UI.createWindow({
        title: theTitle,
        backgroundColor: '#fff'
      });
      label = Ti.UI.createLabel({
        color: '#999',
        text: theText,
        font: {
          fontSize: 20,
          fontFamily: 'Helvetica Neue'
        },
        textAlign: 'center',
        width: 'auto'
      });
      this.win.add(label);
      this.win.addEventListener('click', function() {
        return alert(self.custom1);
      });
    }

    return GenericWindow;

  })();

  root.GenericWindow = GenericWindow;

}).call(this);
