// Generated by CoffeeScript 1.3.1
(function() {
  var Dashboard,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Dashboard = (function(_super) {

    __extends(Dashboard, _super);

    Dashboard.name = 'Dashboard';

    Dashboard.prototype.defaults = {};

    function Dashboard() {
      var dashboardContainer, dashboardLabel, gridButton, gridButtonLabel, listButton, listButtonLabel, titleBar;
      _.extend(this, this.defaults);
      dashboardContainer = Titanium.UI.createView({
        backgroundImage: (Ti.Platform.name !== "android" ? "images/match/layout/bg-menus-iphone.png" : "images/match/layout/bg-menus-android.png"),
        backgroundColor: "transparent",
        top: 44,
        left: 0,
        height: this.getPlatformHeight() - 44,
        width: this.getPlatformWidth()
      });
      titleBar = Titanium.UI.createView({
        backgroundColor: "transparent",
        backgroundImage: "images/match/layout/titlebar-matches.png",
        top: 0,
        left: 0,
        width: this.getPlatformWidth(),
        height: 44,
        isNinePatch: false
      });
      dashboardLabel = Titanium.UI.createLabel({
        text: "Dashboard",
        color: "#ffffff",
        shadowColor: "#000000",
        textAlign: "center",
        font: {
          fontSize: 20,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      gridButton = Titanium.UI.createView({
        backgroundColor: "transparent",
        backgroundImage: "images/match/buttons/btn-dashboard-viewtype-selected.png",
        top: 7,
        left: 8,
        width: 80,
        height: 30
      });
      gridButtonLabel = Titanium.UI.createLabel({
        text: "Grid View",
        color: "#ffffff",
        shadowColor: "#000000",
        left: 11,
        font: {
          fontSize: 13,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      gridButton.add(gridButtonLabel);
      listButton = Titanium.UI.createView({
        backgroundColor: "transparent",
        backgroundImage: "images/match/buttons/btn-dashboard-viewtype.png",
        top: 7,
        right: 8,
        width: 80,
        height: 30
      });
      listButtonLabel = Titanium.UI.createLabel({
        text: "List View",
        color: "#ffffff",
        shadowColor: "#000000",
        left: 11,
        font: {
          fontSize: 13,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      listButton.add(listButtonLabel);
      gridButton.addEventListener("click", function() {
        showGrid();
        gridButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype-selected.png"
        });
        listButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype.png"
        });
        gridButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype-selected.png";
        return listButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype.png";
      });
      listButton.addEventListener("click", function() {
        showList();
        gridButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype-selected.png"
        });
        listButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype.png"
        });
        gridButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype.png";
        return listButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype-selected.png";
      });
      titleBar.add(gridButton);
      titleBar.add(listButton);
      titleBar.add(dashboardLabel);
    }

    return Dashboard;

  })(Template);

  $CS.Views.Dashboard = Dashboard;

}).call(this);
