// Generated by CoffeeScript 1.3.1
(function() {
  var TitleBarView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  TitleBarView = (function(_super) {

    __extends(TitleBarView, _super);

    TitleBarView.name = 'TitleBarView';

    TitleBarView.prototype.defaults = {};

    function TitleBarView(displayType) {
      _.extend(this, this.defaults);
      this.setUp(displayType);
    }

    TitleBarView.prototype.setUp = function(displayType) {
      var dashboardLabel, gridButton, gridButtonLabel, listButton, listButtonLabel;
      this.titleBar = Titanium.UI.createView({
        backgroundColor: "transparent",
        backgroundImage: "images/match/layout/titlebar-matches.png",
        top: 0,
        left: 0,
        width: $CS.Utilities.getPlatformWidth(),
        height: 44,
        isNinePatch: false
      });
      dashboardLabel = Titanium.UI.createLabel({
        text: "Dashboard",
        color: "#ffffff",
        shadowColor: "#000000",
        textAlign: "center",
        font: {
          fontSize: 20,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      gridButton = Titanium.UI.createView({
        backgroundColor: "transparent",
        backgroundImage: displayType === "grid" ? "images/match/buttons/btn-dashboard-viewtype-selected.png" : "images/match/buttons/btn-dashboard-viewtype.png",
        top: 7,
        left: 8,
        width: 80,
        height: 30
      });
      gridButtonLabel = Titanium.UI.createLabel({
        text: "Grid View",
        color: "#ffffff",
        shadowColor: "#000000",
        left: 11,
        font: {
          fontSize: 13,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      gridButton.add(gridButtonLabel);
      listButton = Titanium.UI.createView({
        backgroundColor: "transparent",
        backgroundImage: displayType === "list" ? "images/match/buttons/btn-dashboard-viewtype-selected.png" : "images/match/buttons/btn-dashboard-viewtype.png",
        top: 7,
        right: 8,
        width: 80,
        height: 30
      });
      listButtonLabel = Titanium.UI.createLabel({
        text: "List View",
        color: "#ffffff",
        shadowColor: "#000000",
        left: 11,
        font: {
          fontSize: 13,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      listButton.add(listButtonLabel);
      gridButton.addEventListener("click", function() {
        $CS.Views.Dashboard.showGrid();
        gridButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype-selected.png"
        });
        listButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype.png"
        });
        gridButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype-selected.png";
        return listButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype.png";
      });
      listButton.addEventListener("click", function() {
        $CS.Views.Dashboard.showList();
        gridButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype-selected.png"
        });
        listButton.animate({
          backgroundImage: "images/match/buttons/btn-dashboard-viewtype.png"
        });
        gridButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype.png";
        return listButton.backgroundImage = "images/match/buttons/btn-dashboard-viewtype-selected.png";
      });
      this.titleBar.add(gridButton);
      this.titleBar.add(listButton);
      this.titleBar.add(dashboardLabel);
      return this.titleBar;
    };

    return TitleBarView;

  })($CS.Views.Dashboard);

  $CS.Views.Dashboard.TitleBarView = TitleBarView;

}).call(this);
