// Generated by CoffeeScript 1.3.3
(function() {
  var me;

  me = this;

  this.ballCategorySelectorContainer = Ti.UI.createImageView({
    backgroundImage: "images/match/layout/bg-endgame.png",
    backgroundColor: "transparent",
    top: 44,
    left: 0,
    height: getPlatformHeight() - 44,
    width: getPlatformWidth()
  });

  this.ballCategorySelectorContainer.visible = false;

  this.view.add(this.ballCategorySelectorContainer);

  this.ballCategorySelector = Ti.UI.createView({
    backgroundImage: "images/match/8ball/layout/bg-select-suit.png",
    height: 280,
    width: 275,
    top: 88
  });

  this.ballCategorySelector.visible = false;

  this.ballCategorySelectorPlayerName = Ti.UI.createLabel({
    text: "",
    color: "#afd5f1",
    top: 6,
    left: 0,
    height: 20,
    width: 275,
    textAlign: "center",
    font: {
      fontSize: 14,
      fontWeight: "bold",
      fontFamily: "HelveticaNeue-Bold"
    }
  });

  this.ballCategorySelector.add(this.ballCategorySelectorPlayerName);

  this.ballCategoryButtonContainer = Ti.UI.createView({
    backgroundColor: "transparent",
    top: 55,
    left: 9,
    height: 126,
    width: 257
  });

  this.solidCategoryButton = Ti.UI.createImageView({
    backgroundImage: "images/match/layout/bg_play_gamebutton.png",
    backgroundColor: "transparent",
    top: 0,
    left: 0,
    height: 126,
    width: 124
  });

  this.solidCategoryButtonActive = Ti.UI.createView({
    backgroundImage: "images/match/layout/bg_play_gamebutton_active.png",
    backgroundColor: "transparent",
    top: 0,
    left: 0,
    height: 126,
    width: 124
  });

  this.solidCategoryButtonActive.visible = false;

  this.solidCategoryButtonIcon = Ti.UI.createImageView({
    backgroundImage: "images/match/icons/icon_gamebutton_8ball.png",
    backgroundColor: "transparent",
    top: 5,
    left: 21,
    height: 88,
    width: 88
  });

  this.solidCategoryButtonLabel = Ti.UI.createLabel({
    text: "Solids",
    backgroundColor: "transparent",
    top: 93,
    left: 3,
    height: 25,
    width: 124,
    textAlign: "center",
    color: "#ffffff",
    font: {
      fontSize: 20,
      fontWeight: "bold",
      fontFamily: "HelveticaNeue-Bold"
    }
  });

  this.solidCategoryClick = function() {
    if (me.solidCategoryButtonActive.visible === false) {
      me.solidCategoryButtonActive.visible = true;
      me.solidCategoryButton.visible = false;
      me.stripeCategoryButtonActive.visible = false;
      return me.stripeCategoryButton.visible = true;
    }
  };

  this.solidCategoryButtonIcon.addEventListener("click", this.solidCategoryClick);

  this.solidCategoryButton.addEventListener("click", this.solidCategoryClick);

  this.ballCategoryButtonContainer.add(this.solidCategoryButtonActive);

  this.ballCategoryButtonContainer.add(this.solidCategoryButton);

  this.ballCategoryButtonContainer.add(this.solidCategoryButtonIcon);

  this.ballCategoryButtonContainer.add(this.solidCategoryButtonLabel);

  this.stripeCategoryButton = Ti.UI.createImageView({
    backgroundImage: "images/match/layout/bg_play_gamebutton.png",
    backgroundColor: "transparent",
    top: 0,
    left: 132,
    height: 126,
    width: 124
  });

  this.stripeCategoryButton.visible = true;

  this.stripeCategoryButtonActive = Ti.UI.createView({
    backgroundImage: "images/match/layout/bg_play_gamebutton_active.png",
    backgroundColor: "transparent",
    top: 0,
    left: 132,
    height: 126,
    width: 124
  });

  this.stripeCategoryButtonActive.visible = false;

  this.stripeCategoryButtonIcon = Ti.UI.createView({
    backgroundImage: "images/match/icons/icon_gamebutton_9ball.png",
    backgroundColor: "transparent",
    top: 5,
    left: 152,
    height: 88,
    width: 88
  });

  this.stripeCategoryButtonLabel = Ti.UI.createLabel({
    text: "Stripes",
    backgroundColor: "transparent",
    top: 93,
    left: 134,
    height: 25,
    width: 124,
    color: "#ffffff",
    textAlign: "center",
    font: {
      fontSize: 20,
      fontWeight: "bold",
      fontFamily: "HelveticaNeue-Bold"
    }
  });

  this.stripeCategoryClick = function() {
    if (me.stripeCategoryButtonActive.visible === false) {
      me.solidCategoryButtonActive.visible = false;
      me.solidCategoryButton.visible = true;
      me.stripeCategoryButtonActive.visible = true;
      return me.stripeCategoryButton.visible = false;
    }
  };

  this.stripeCategoryButton.addEventListener("click", this.stripeCategoryClick);

  this.stripeCategoryButtonIcon.addEventListener("click", this.stripeCategoryClick);

  this.ballCategoryButtonContainer.add(this.stripeCategoryButtonActive);

  this.ballCategoryButtonContainer.add(this.stripeCategoryButton);

  this.ballCategoryButtonContainer.add(this.stripeCategoryButtonIcon);

  this.ballCategoryButtonContainer.add(this.stripeCategoryButtonLabel);

  this.ballCategorySelector.add(this.ballCategoryButtonContainer);

  this.ballCategoryContinueButton = Ti.UI.createImageView({
    backgroundImage: "images/match/8ball/buttons/btn-selectandcontinue.png",
    backgroundColor: "transparent",
    top: 187,
    left: 10,
    height: 35,
    width: 254
  });

  this.ballCategoryCancelButton = Ti.UI.createImageView({
    backgroundImage: "images/match/8ball/buttons/btn-cancel.png",
    backgroundColor: "transparent",
    top: 229,
    left: 10,
    height: 35,
    width: 254
  });

  this.ballCategoryContinueButton.addEventListener("click", function() {
    if (me.stripeCategoryButtonActive.visible === true) {
      if (me.currentMatch.PlayerOne.CurrentlyUp === false) {
        me.currentMatch.CurrentGame.setPlayerOneBallTypeToStriped();
      } else {
        me.currentMatch.CurrentGame.setPlayerTwoBallTypeToStriped();
      }
      return me.saveAndUpdateUI();
    } else if (me.solidCategoryButtonActive.visible === true) {
      if (me.currentMatch.PlayerOne.CurrentlyUp === false) {
        me.currentMatch.CurrentGame.setPlayerOneBallTypeToSolid();
      } else {
        me.currentMatch.CurrentGame.setPlayerTwoBallTypeToSolid();
      }
      return me.saveAndUpdateUI();
    } else {
      return me.showOverlay("Must pick ball category first!", 300);
    }
  });

  this.ballCategoryCancelButton.addEventListener("click", function() {
    if (me.currentMatch.Ended !== true) {
      return me.hideBallCategorySelector();
    } else {
      return me.showOverlay("Match has ended, must pick category!", 300);
    }
  });

  this.ballCategorySelector.add(this.ballCategoryContinueButton);

  this.ballCategorySelector.add(this.ballCategoryCancelButton);

  this.view.add(this.ballCategorySelector);

  this.showBallCategorySelector = function() {
    this.stripeCategoryButtonActive.visible = false;
    this.solidCategoryButtonActive.visible = false;
    this.stripeCategoryButton.visible = true;
    this.solidCategoryButton.visible = true;
    this.ballCategorySelectorPlayerName.text = (this.currentMatch.PlayerOne.CurrentlyUp === true ? this.currentMatch.PlayerTwo.getFirstNameWithInitials() : this.currentMatch.PlayerOne.getFirstNameWithInitials());
    this.ballCategorySelector.visible = true;
    return this.ballCategorySelectorContainer.visible = true;
  };

  this.hideBallCategorySelector = function() {
    this.ballCategorySelectorContainer.visible = false;
    return this.ballCategorySelector.visible = false;
  };

}).call(this);
