// Generated by CoffeeScript 1.3.1
(function() {
  var me;

  me = this;

  this.ballSelectorContainer = Ti.UI.createImageView({
    backgroundColor: "transparent",
    top: 0,
    left: 0,
    height: getPlatformHeight(),
    width: getPlatformWidth()
  });

  this.ballSelectorContainer.visible = false;

  this.ballView = Ti.UI.createView({
    top: (Ti.Platform.name !== "android" ? 125 : 150),
    height: 235,
    width: 251
  });

  this.ballOneButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/1ball-large.png",
    top: 10,
    left: 102,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballOneBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/1ball-large-inactive.png",
    top: 10,
    left: 102,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballOneShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 0,
    left: 92,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballTwoButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/2ball-large.png",
    top: 86,
    left: 148,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballTwoBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/2ball-large-inactive.png",
    top: 86,
    left: 148,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballTwoShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 76,
    left: 138,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballThreeButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/3ball-large.png",
    top: 162,
    left: 148,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballThreeBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/3ball-large-inactive.png",
    top: 162,
    left: 148,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballThreeShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 152,
    left: 138,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballFourButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/4ball-large.png",
    top: 124,
    left: 125,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFourBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/4ball-large-inactive.png",
    top: 124,
    left: 125,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFourShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 114,
    left: 115,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballFiveButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/5ball-large.png",
    top: 162,
    left: 56,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFiveBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/5ball-large-inactive.png",
    top: 162,
    left: 56,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFiveShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 152,
    left: 46,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballSixButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/6ball-large.png",
    top: 124,
    left: 33,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballSixBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/6ball-large-inactive.png",
    top: 124,
    left: 33,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballSixShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 114,
    left: 23,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballSevenButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/7ball-large.png",
    top: 48,
    left: 79,
    opacity: 1,
    width: 47,
    height: 47
  });

  this.ballSevenBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/7ball-large-inactive.png",
    top: 48,
    left: 79,
    opacity: 1,
    width: 47,
    height: 47
  });

  this.ballSevenShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 38,
    left: 69,
    opacity: 1,
    width: 66,
    height: 66
  });

  this.ballEightButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/8ball-large.png",
    top: 86,
    left: 102,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballEightBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/8ball-large-inactive.png",
    top: 86,
    left: 102,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballEightShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 76,
    left: 92,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballNineButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/9ball-large.png",
    top: 48,
    left: 125,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballNineBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/9ball-large-inactive.png",
    top: 48,
    left: 125,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballNineShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 38,
    left: 115,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballTenButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/10ball-large.png",
    top: 162,
    left: 10,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballTenBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/10ball-large-inactive.png",
    top: 162,
    left: 10,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballTenShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 152,
    left: 0,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballElevenButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/11ball-large.png",
    top: 162,
    left: 194,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballElevenBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/11ball-large-inactive.png",
    top: 162,
    left: 194,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballElevenShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 152,
    left: 184,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballTwelveButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/12ball-large.png",
    top: 162,
    left: 102,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballTwelveBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/12ball-large-inactive.png",
    top: 162,
    left: 102,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballTwelveShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 152,
    left: 92,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballThirteenButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/13ball-large.png",
    top: 124,
    left: 79,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballThirteenBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/13ball-large-inactive.png",
    top: 124,
    left: 79,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballThirteenShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 114,
    left: 69,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballFourteenButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/14ball-large.png",
    top: 86,
    left: 56,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFourteenBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/14ball-large-inactive.png",
    top: 86,
    left: 56,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFourteenShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 76,
    left: 46,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballFifteenButton = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/15ball-large.png",
    top: 124,
    left: 171,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFifteenBg = Ti.UI.createImageView({
    color: "#FFF",
    backgroundImage: "images/match/8ball/largeballs/15ball-large-inactive.png",
    top: 124,
    left: 171,
    opacity: 1,
    width: 47,
    height: 47,
    isNinePatch: false
  });

  this.ballFifteenShadow = Ti.UI.createImageView({
    backgroundImage: "images/match/largeballs/shadow-large-balls.png",
    top: 114,
    left: 161,
    opacity: 1,
    width: 66,
    height: 66,
    isNinePatch: false
  });

  this.ballSelectorContainer.addEventListener("click", function() {
    return me.closeBallSelector();
  });

  this.ballOneButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballOneButton.top, me.ballOneButton.left, me.ballOneButton.height, me.ballOneButton.width, "1");
  });

  this.ballTwoButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballTwoButton.top, me.ballTwoButton.left, me.ballTwoButton.height, me.ballTwoButton.width, "2");
  });

  this.ballThreeButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballThreeButton.top, me.ballThreeButton.left, me.ballThreeButton.height, me.ballThreeButton.width, "3");
  });

  this.ballFourButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballFourButton.top, me.ballFourButton.left, me.ballFourButton.height, me.ballFourButton.width, "4");
  });

  this.ballFiveButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballFiveButton.top, me.ballFiveButton.left, me.ballFiveButton.height, me.ballFiveButton.width, "5");
  });

  this.ballSixButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballSixButton.top, me.ballSixButton.left, me.ballSixButton.height, me.ballSixButton.width, "6");
  });

  this.ballSevenButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballSevenButton.top, me.ballSevenButton.left, me.ballSevenButton.height, me.ballSevenButton.width, "7");
  });

  this.ballEightButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballEightButton.top, me.ballEightButton.left, me.ballEightButton.height, me.ballEightButton.width, "8");
  });

  this.ballNineButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballNineButton.top, me.ballNineButton.left, me.ballNineButton.height, me.ballNineButton.width, "9");
  });

  this.ballTenButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballTenButton.top, me.ballTenButton.left, me.ballTenButton.height, me.ballTenButton.width, "10");
  });

  this.ballElevenButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballElevenButton.top, me.ballElevenButton.left, me.ballElevenButton.height, me.ballElevenButton.width, "11");
  });

  this.ballTwelveButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballTwelveButton.top, me.ballTwelveButton.left, me.ballTwelveButton.height, me.ballTwelveButton.width, "12");
  });

  this.ballThirteenButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballThirteenButton.top, me.ballThirteenButton.left, me.ballThirteenButton.height, me.ballThirteenButton.width, "13");
  });

  this.ballFourteenButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballFourteenButton.top, me.ballFourteenButton.left, me.ballFourteenButton.height, me.ballFourteenButton.width, "14");
  });

  this.ballFifteenButton.addEventListener("click", function() {
    return me.showBallSelector(me.ballFifteenButton.top, me.ballFifteenButton.left, me.ballFifteenButton.height, me.ballFifteenButton.width, "15");
  });

  this.ballView.add(this.ballOneShadow);

  this.ballView.add(this.ballTwoShadow);

  this.ballView.add(this.ballThreeShadow);

  this.ballView.add(this.ballFourShadow);

  this.ballView.add(this.ballFiveShadow);

  this.ballView.add(this.ballSixShadow);

  this.ballView.add(this.ballSevenShadow);

  this.ballView.add(this.ballEightShadow);

  this.ballView.add(this.ballNineShadow);

  this.ballView.add(this.ballTenShadow);

  this.ballView.add(this.ballElevenShadow);

  this.ballView.add(this.ballTwelveShadow);

  this.ballView.add(this.ballThirteenShadow);

  this.ballView.add(this.ballFourteenShadow);

  this.ballView.add(this.ballFifteenShadow);

  this.ballView.add(this.ballOneBg);

  this.ballView.add(this.ballTwoBg);

  this.ballView.add(this.ballThreeBg);

  this.ballView.add(this.ballFourBg);

  this.ballView.add(this.ballFiveBg);

  this.ballView.add(this.ballSixBg);

  this.ballView.add(this.ballSevenBg);

  this.ballView.add(this.ballEightBg);

  this.ballView.add(this.ballNineBg);

  this.ballView.add(this.ballTenBg);

  this.ballView.add(this.ballElevenBg);

  this.ballView.add(this.ballTwelveBg);

  this.ballView.add(this.ballThirteenBg);

  this.ballView.add(this.ballFourteenBg);

  this.ballView.add(this.ballFifteenBg);

  this.ballView.add(this.ballOneButton);

  this.ballView.add(this.ballTwoButton);

  this.ballView.add(this.ballThreeButton);

  this.ballView.add(this.ballFourButton);

  this.ballView.add(this.ballFiveButton);

  this.ballView.add(this.ballSixButton);

  this.ballView.add(this.ballSevenButton);

  this.ballView.add(this.ballEightButton);

  this.ballView.add(this.ballNineButton);

  this.ballView.add(this.ballTenButton);

  this.ballView.add(this.ballElevenButton);

  this.ballView.add(this.ballTwelveButton);

  this.ballView.add(this.ballThirteenButton);

  this.ballView.add(this.ballFourteenButton);

  this.ballView.add(this.ballFifteenButton);

  this.view.add(this.ballSelectorContainer);

  this.view.add(this.ballView);

  this.showBallSelector = function(top, left, height, width, ballNumber) {
    var centerLeft, centerTop;
    centerTop = (height / 2) + top + me.ballView.top;
    centerLeft = (width / 2) + left + (me.getPlatformWidth() / 2) - (me.ballView.width / 2);
    return me.centerBallSelector(centerTop, centerLeft, ballNumber);
  };

  this.closeBallSelector = function() {
    return this.closeOverlay();
  };

  this.updateShownBalls = function() {
    var ballsIn;
    ballsIn = this.currentMatch.CurrentGame.getBallsHitIn();
    this.ballOneButton.visible = !(ballsIn.exists(1));
    this.ballTwoButton.visible = !(ballsIn.exists(2));
    this.ballThreeButton.visible = !(ballsIn.exists(3));
    this.ballFourButton.visible = !(ballsIn.exists(4));
    this.ballFiveButton.visible = !(ballsIn.exists(5));
    this.ballSixButton.visible = !(ballsIn.exists(6));
    this.ballSevenButton.visible = !(ballsIn.exists(7));
    this.ballEightButton.visible = !(ballsIn.exists(8));
    this.ballNineButton.visible = !(ballsIn.exists(9));
    this.ballTenButton.visible = !(ballsIn.exists(10));
    this.ballElevenButton.visible = !(ballsIn.exists(11));
    this.ballTwelveButton.visible = !(ballsIn.exists(12));
    this.ballThirteenButton.visible = !(ballsIn.exists(13));
    this.ballFourteenButton.visible = !(ballsIn.exists(14));
    this.ballFifteenButton.visible = !(ballsIn.exists(15));
    this.ballOneShadow.visible = !(ballsIn.exists(1));
    this.ballTwoShadow.visible = !(ballsIn.exists(2));
    this.ballThreeShadow.visible = !(ballsIn.exists(3));
    this.ballFourShadow.visible = !(ballsIn.exists(4));
    this.ballFiveShadow.visible = !(ballsIn.exists(5));
    this.ballSixShadow.visible = !(ballsIn.exists(6));
    this.ballSevenShadow.visible = !(ballsIn.exists(7));
    this.ballEightShadow.visible = !(ballsIn.exists(8));
    this.ballNineShadow.visible = !(ballsIn.exists(9));
    this.ballTenShadow.visible = !(ballsIn.exists(10));
    this.ballElevenShadow.visible = !(ballsIn.exists(11));
    this.ballTwelveShadow.visible = !(ballsIn.exists(12));
    this.ballThirteenShadow.visible = !(ballsIn.exists(13));
    this.ballFourteenShadow.visible = !(ballsIn.exists(14));
    this.ballFifteenShadow.visible = !(ballsIn.exists(15));
    this.updateSolidBalls();
    return this.updateStripedBalls();
  };

}).call(this);
