// Generated by CoffeeScript 1.3.1
(function() {
  var currentTeamSigning, me;

  me = this;

  currentTeamSigning = null;

  this.signatureViewOverlay = Ti.UI.createView({
    backgroundImage: "images/match/layout/bg-sign-scoresheet-android.png",
    height: 452,
    width: 320,
    visible: false
  });

  this.signatureView = Ti.UI.createPaint({
    right: 116,
    top: 50,
    height: 365,
    width: 40,
    backgroundColor: "#ffffff"
  });

  this.signatureView.visible = false;

  this.isSignatureTeamNameTurned = false;

  this.signatureTeamName = Ti.UI.createLabel({
    text: "",
    top: 100,
    left: 150,
    height: 20,
    width: 220,
    backgroundColor: "transparent",
    textAlign: "left",
    font: {
      fontSize: 15,
      fontWeight: "bold",
      fontFamily: "HelveticaNeue-Bold"
    }
  });

  this.isSignatureTeamNumberTurned = false;

  this.signatureTeamNumber = Ti.UI.createLabel({
    text: "Team 123",
    left: 80,
    bottom: 40,
    height: 20,
    width: 220,
    backgroundColor: "transparent",
    textAlign: "right",
    font: {
      fontSize: 15,
      fontWeight: "bold",
      fontFamily: "HelveticaNeue-Bold"
    }
  });

  this.signatureBackButton = Ti.UI.createImageView({
    height: 61,
    width: 31,
    top: 8,
    right: 7,
    backgroundColor: "transparent"
  });

  this.signatureBackButton.addEventListener("click", function() {
    return me.hideSignatureView();
  });

  this.signatureNextButton = Ti.UI.createImageView({
    height: 61,
    width: 31,
    right: 8,
    bottom: 13,
    backgroundColor: "transparent"
  });

  this.signatureNextButton.addEventListener("click", function() {
    return me.setupSignatureOverlay();
  });

  this.signatureSendButton = Ti.UI.createImageView({
    height: 135,
    width: 27,
    right: 260,
    top: 232,
    backgroundColor: "transparent"
  });

  this.signatureSendButton.addEventListener("click", function() {
    return DataService.sendSignature(me.signatureView.toImage());
  });

  this.protestMatchButton = Ti.UI.createImageView({
    height: 115,
    width: 27,
    right: 260,
    top: 111,
    backgroundColor: "transparent"
  });

  this.protestMatchButton.addEventListener("click", function() {});

  this.view.add(this.signatureViewOverlay);

  this.signatureViewOverlay.add(this.signatureTeamName);

  this.signatureViewOverlay.add(this.signatureTeamNumber);

  this.signatureViewOverlay.add(this.signatureBackButton);

  this.signatureViewOverlay.add(this.signatureNextButton);

  this.signatureViewOverlay.add(this.signatureSendButton);

  this.signatureViewOverlay.add(this.protestMatchButton);

  this.view.add(this.signatureView);

  this.openSignatureView = function() {
    me.setupSignatureOverlay();
    me.signatureViewOverlay.visible = true;
    return me.signatureView.visible = true;
  };

  this.hideSignatureView = function() {
    me.signatureViewOverlay.visible = false;
    return me.signatureView.visible = false;
  };

  this.matchSignedCallBack = function() {
    return me.setupSignatureOverlay();
  };

  this.setupSignatureOverlay = function() {
    this.changeTeamSigning();
    if (this.leagueMatch.HomeTeamNumber === currentTeamSigning) {
      this.signatureTeamName.text = this.leagueMatch.HomeTeamName;
      return this.signatureTeamNumber.text = "Team " + this.leagueMatch.HomeTeamNumber;
    } else if (this.leagueMatch.AwayTeamNumber === currentTeamSigning) {
      this.signatureTeamName.text = this.leagueMatch.AwayTeamName;
      return this.signatureTeamNumber.text = "Team " + this.leagueMatch.AwayTeamNumber;
    } else {

    }
  };

  this.changeTeamSigning = function() {
    if (currentTeamSigning == null) {
      if (this.leagueMatch.HomeTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.HomeTeamNumber;
      } else {
        if (this.leagueMatch.AwayTeamSigned === false) {
          return currentTeamSigning = this.leagueMatch.AwayTeamNumber;
        }
      }
    } else if (currentTeamSigning === this.leagueMatch.HomeTeamNumber) {
      if (this.leagueMatch.HomeTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.HomeTeamNumber;
      } else if (this.leagueMatch.AwayTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.AwayTeamNumber;
      } else {
        return currentTeamSigning = null;
      }
    } else if (currentTeamSigning === this.leagueMatch.AwayTeamNumber) {
      if (this.leagueMatch.AwayTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.HomeTeamNumber;
      } else if (this.leagueMatch.HomeTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.AwayTeamNumber;
      } else {
        return currentTeamSigning = null;
      }
    } else {
      if (this.leagueMatch.HomeTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.HomeTeamNumber;
      } else if (this.leagueMatch.AwayTeamSigned === false) {
        return currentTeamSigning = this.leagueMatch.AwayTeamNumber;
      } else {
        return currentTeamSigning = null;
      }
    }
  };

}).call(this);
