// Generated by CoffeeScript 1.3.3
(function() {
  var DataService,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DataService = (function(_super) {

    __extends(DataService, _super);

    DataService.prototype.defaults = {};

    function DataService(options) {
      if (options == null) {
        options = {};
      }
      _.extend(this, this.defaults);
      ({
        email: "i.wooten@gmail.com"
      });
      this.db = this.openDatabase();
    }

    DataService.prototype.undoMatch = function(originalId) {
      var match, row;
      try {
        row = this.db.execute("SELECT ID,OriginalId,Match FROM Matches WHERE OriginalId = " + originalId + " OR ID = " + originalId + " ORDER BY ID DESC LIMIT 1 OFFSET 1");
        if (!row.isValidRow()) {
          row.close();
          this.db.close();
          return null;
        }
        match = new Function("return" + row.fieldByName("Match"))();
        match.OriginalId = originalId;
        this.db.execute("DELETE FROM Matches WHERE OriginalId = " + originalId + " AND ID > " + row.fieldByName("ID") + " AND ID != OriginalId");
        row.close();
        this.db.close();
        return match;
      } catch (e) {
        row.close();
        return this.db.close();
      }
    };

    DataService.prototype.saveMatch = function(match, setOriginalIdCallback) {
      try {
        if (!(match.OriginalId != null) || match.OriginalId === 0) {
          leagueMatch.SmallJSON = true;
          this.db.execute("INSERT INTO Matches (Match, EnteredDateTime) VALUES(?, ?)", this.convertToJSONString(match), "DATETIME(NOW)");
          setOriginalIdCallback(this.db.lastInsertRowId);
          this.db.execute("UPDATE Matches SET OriginalId = " + this.db.lastInsertRowId + " WHERE ID = " + this.db.lastInsertRowId);
          this.db.close();
          return;
        }
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.log("@db rounded OId", parseInt(match.OriginalId));
        }
        this.db.execute("INSERT INTO Matches (OriginalId, Match, EnteredDateTime) VALUES(?, ?, ?)", match.OriginalId.toString(), this.convertToJSONString(match), "DATETIME(NOW)");
        this.db.close();
      } catch (e) {
        return this.db.close();
      }
    };

    DataService.prototype.getLeagueMatch = function(leagueMatchId) {
      var leagueMatch, row;
      try {
        row = this.db.execute("SELECT LeagueMatch FROM LeagueMatches WHERE ID = " + leagueMatchId);
        leagueMatch = new Function("return" + row.fieldByName("LeagueMatch"))();
        leagueMatch.LeagueMatchId = leagueMatchId;
        row.close();
        this.db.close();
        return leagueMatch;
      } catch (e) {
        row.close();
        return this.db.close();
      }
    };

    DataService.prototype.saveLeagueMatch = function(leagueMatch, setLeagueMatchIdCallback) {
      try {
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.log(this.convertToJSONString(leagueMatch));
        }
        if (!(leagueMatch.LeagueMatchId != null) || leagueMatch.LeagueMatchId === 0) {
          leagueMatch.SmallJSON = true;
          this.db.execute("INSERT INTO LeagueMatches (LeagueMatch, EnteredDateTime) VALUES(?, ?)", this.convertToJSONString(leagueMatch), "DATETIME(NOW)");
          setLeagueMatchIdCallback(this.db.lastInsertRowId);
          this.db.close();
          return;
        }
        this.db.execute("UPDATE LeagueMatches SET SET LeagueMatch = " + this.convertToJSONString(leagueMatch) + " WHERE ID = " + leagueMatch.LeagueMatchId);
        setLeagueMatchIdCallback(this.db.lastInsertRowId);
        this.db.close();
      } catch (e) {
        return this.db.close();
      }
    };

    DataService.prototype.sendSignature = function(imageData) {
      var xhr;
      xhr = typeof Ti !== "undefined" && Ti !== null ? Ti.Network.createHTTPClient() : void 0;
      xhr.setTimeout(9999999);
      xhr.onload = function() {
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info("in utf-8 onload for POST");
        }
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info(this.responseText);
        }
        return typeof Ti !== "undefined" && Ti !== null ? Ti.UI.createAlertDialog({
          title: "Success:",
          message: this.responseText
        }).show() : void 0;
      };
      xhr.onerror = function(e) {
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info("in utf-8 error for POST");
        }
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info(e.error);
        }
        return typeof Ti !== "undefined" && Ti !== null ? Ti.UI.createAlertDialog({
          title: "Error:",
          message: e.error
        }).show() : void 0;
      };
      xhr.open("POST", "http://cuescoreapp.com/signature/post/");
      return xhr.send({
        teamid: "new",
        matchid: "new",
        gametype: null,
        playerid: "new",
        mimetype: "png",
        imagedata: imageData.data
      });
    };

    DataService.prototype.sendLeagueMatch = function(leagueMatch) {
      var xhr;
      xhr = typeof Ti !== "undefined" && Ti !== null ? Ti.Network.createHTTPClient({
        timeout: 9999999999999
      }) : void 0;
      xhr.onload = function() {
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info("in utf-8 onload for POST");
        }
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info(this.responseText);
        }
        return typeof Ti !== "undefined" && Ti !== null ? Ti.UI.createAlertDialog({
          title: "Success:",
          message: this.responseText
        }).show() : void 0;
      };
      xhr.onerror = function(e) {
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info("in utf-8 error for POST");
        }
        if (typeof Ti !== "undefined" && Ti !== null) {
          Ti.API.info(e.error);
        }
        return typeof Ti !== "undefined" && Ti !== null ? Ti.UI.createAlertDialog({
          title: "Error:",
          message: e.error
        }).show() : void 0;
      };
      xhr.open("POST", "http://cuescoreapp.com/leaguematch/post/");
      return xhr.send({
        userid: "123",
        apikey: "secret",
        format: "json",
        sendToEmail: this.email,
        matchid: "new",
        matchdata: this.convertToJSONString(leagueMatch),
        gametype: this.leagueMatch.GameType
      });
    };

    DataService.prototype.setupLocalDatabase = function() {
      this.db = this.openDatabase();
      this.db.execute("CREATE TABLE IF NOT EXISTS LeagueMatches (ID INTEGER PRIMARY KEY, LeagueMatch BLOB, Sent BOOLEAN, EnteredDateTime DATETIME)");
      this.db.execute("CREATE TABLE IF NOT EXISTS Matches (ID INTEGER PRIMARY KEY, OriginalId Integer, LeagueMatchId Integer, Match BLOB, EnteredDateTime DATETIME)");
      this.db.execute("DELETE FROM LeagueMatches");
      this.db.execute("DELETE FROM Matches");
      return this.db.close();
    };

    DataService.prototype.openDatabase = function() {
      if (typeof Ti !== "undefined" && Ti !== null) {
        return Ti.Database.open("CueScore");
      } else {
        return {
          close: function() {}
        };
      }
    };

    DataService.prototype.convertToJSONString = function(myObject) {
      return JSON.stringify(myObject);
    };

    DataService.prototype.parseJSONString = function(myJSONtext, emptyObject) {
      return emptyObject.fromJSON(myJSONtext);
    };

    DataService.prototype.var_dump = function(obj) {
      if (typeof obj === "object") {
        return "Type: " + typeof obj + (obj.constructor ? "\nConstructor: " + obj.constructor : "") + "\nValue: " + obj;
      } else {
        return "Type: " + typeof obj + "\nValue: " + obj;
      }
    };

    return DataService;

  })($CS.Utilities);

  $CS.Utilities.DataService = DataService;

}).call(this);
