// Generated by CoffeeScript 1.3.3
(function() {
  var after, console, every, say;

  console = {
    log: function(str) {
      return Ti.API.info(str);
    },
    warn: function(str) {
      return Ti.API.warn(str);
    },
    error: function(str) {
      return Ti.API.error(str);
    }
  };

  say = function(msg) {
    return alert(msg);
  };

  after = function(ms, cb) {
    return setTimeout(cb, ms);
  };

  every = function(ms, cb) {
    return setInterval(cb, ms);
  };

}).call(this);
