// Generated by CoffeeScript 1.3.1
(function() {
  var Match,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Match = (function(_super) {

    __extends(Match, _super);

    Match.name = 'Match';

    function Match() {
      return Match.__super__.constructor.apply(this, arguments);
    }

    Match.prototype.defaults = {
      name: "Fetus",
      age: 0,
      children: []
    };

    Match.prototype.initialize = function() {
      _.extend(this, this.defaults);
      console.log("Welcome to this world");
      return this.bind("change:name", function() {
        var name;
        name = this.get("name");
        return console.log("Changed my name to " + name);
      });
    };

    Match.prototype.replaceNameAttr = function(name) {
      return this.set({
        name: name
      });
    };

    return Match;

  })(Backbone.Model);

  $CS.Models.Match = Match;

}).call(this);
