// Generated by CoffeeScript 1.3.1
(function() {
  var Team,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Team = (function(_super) {

    __extends(Team, _super);

    Team.name = 'Team';

    function Team() {
      return Team.__super__.constructor.apply(this, arguments);
    }

    Team.prototype.defaults = {};

    Team.prototype.initialize = function() {
      return _.extend(this, this.defaults);
    };

    return Team;

  })(Backbone.Model);

  $CS.Models.Team = Team;

}).call(this);
