// Generated by CoffeeScript 1.3.1
(function() {

  describe("League", function() {
    var attributes, league;
    league = void 0;
    attributes = void 0;
    beforeEach(function() {
      league = new $CS.Models.League();
      return attributes = league.attributes;
    });
    return describe("Constructor", function() {
      it("should be able to create a new League", function() {
        league.initialize();
        return expect(league).not.toBeUndefined();
      });
      it("should contain default attributes", function() {
        expect(attributes.name).toBeDefined();
        expect(attributes.age).toBeDefined();
        expect(attributes.children).toBeDefined();
        expect(attributes.name).toEqual("Fetus");
        expect(attributes.age).toEqual(0);
        return expect(attributes.children).toEqual([]);
      });
      return it("should store the parameters", function() {
        var options;
        league = new $CS.Models.League(options = {
          name: "Isaac Wooten",
          age: 1,
          children: []
        });
        attributes = league.attributes;
        expect(attributes.name).toEqual("Isaac Wooten");
        expect(attributes.age).toEqual(1);
        return expect(attributes.children).toEqual([]);
      });
    });
  });

}).call(this);
