// Generated by CoffeeScript 1.3.1
(function() {

  this.startMatchOverlayContainer = Ti.UI.createView({
    backgroundColor: "#ffffff",
    top: 44,
    left: 0,
    height: this.getPlatformHeight() - 44,
    width: this.getPlatformWidth()
  });

  this.startMatchOverlayContainer.visible = true;

  this.view.add(this.startMatchOverlayContainer);

  this.showStartMatchOverlay = function() {};

}).call(this);
