// Generated by CoffeeScript 1.3.1
(function() {
  var actInd, hideIndicator, indWin, matchSetup, showIndicator, stopIndicator;

  showIndicator = function(title) {
    var actInd, indView, indWin, indicatorShowing, message;
    indicatorShowing = true;
    indWin = Ti.UI.createWindow({
      width: 150,
      height: 150
    });
    indView = Ti.UI.createView({
      width: 150,
      height: 150,
      backgroundColor: "#000",
      borderRadius: 10,
      opacity: 0.7
    });
    indWin.add(indView);
    actInd = Ti.UI.createImageView({
      top: 20,
      duration: 300,
      defaultImage: "images/dashboard/loading/loading1.png",
      images: ["images/dashboard/loading/loading1.png", "images/dashboard/loading/loading2.png", "images/dashboard/loading/loading3.png", "images/dashboard/loading/loading4.png", "images/dashboard/loading/loading5.png"],
      height: 88,
      width: 88
    });
    indWin.add(actInd);
    message = Ti.UI.createLabel({
      text: title,
      color: "#fff",
      font: {
        fontSize: 20,
        fontWeight: "bold"
      },
      top: 110,
      left: 30
    });
    indWin.add(message);
    actInd.start();
    return indWin.open();
  };

  hideIndicator = function() {
    var indicatorShowing;
    actInd.stop();
    indWin.close({
      opacity: 0,
      duration: 500
    });
    return indicatorShowing = false;
  };

  stopIndicator = function() {
    return actInd.stop();
  };

  matchSetup = function() {
    var me;
    me = this;
    Ti.include("/js/pages/match.js");
    Ti.include("/js/json2.js");
    Ti.include("/js/NineBall/NineBallGame.js");
    Ti.include("/js/NineBall/NineBallPlayer.js");
    Ti.include("/js/NineBall/NineBallLeagueMatch.js");
    Ti.include("/js/NineBall/NineBallMatch.js");
    Ti.include("/js/NineBall/NineBallRanks.js");
    Ti.include("/js/EightBall/EightBallGame.js");
    Ti.include("/js/EightBall/EightBallPlayer.js");
    Ti.include("/js/EightBall/EightBallLeagueMatch.js");
    Ti.include("/js/EightBall/EightBallMatch.js");
    Ti.include("/js/EightBall/EightBallRanks.js");
    Ti.include("/js/Services/DataService.js");
    try {
      Ti.include("/js/Common.js");
    } catch (_error) {}
    this.matchSetupWindow = Ti.UI.createWindow({
      orientationModes: [Ti.UI.PORTRAIT],
      title: "Play"
    });
    this.matchSetupTitleBar = Ti.UI.createView({
      backgroundColor: "transparent",
      backgroundImage: "images/match/layout/titlebar-matches.png",
      top: 0,
      left: 0,
      width: getPlatformWidth(),
      height: 44
    });
    this.playLabel = Ti.UI.createLabel({
      text: "Play",
      color: "#ffffff",
      shadowColor: "#000000",
      textAlign: "center",
      font: {
        fontSize: 20,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.dashboardButton = Ti.UI.createView({
      backgroundColor: "transparent",
      backgroundImage: "images/match/buttons/btn-tabmenu-backto-dashboard.png",
      top: 7,
      left: 8,
      width: 93,
      height: 30
    });
    this.dashboardButtonLabel = Ti.UI.createLabel({
      text: "Dashboard",
      color: "#ffffff",
      shadowColor: "#000000",
      left: 13,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.dashboardButton.add(this.dashboardButtonLabel);
    this.dashboardButton.addEventListener("click", function() {
      me.matchSetupWindow.close();
      return me.dashboardWindow.show();
    });
    this.matchSetupDoneButton = Ti.UI.createView({
      backgroundColor: "transparent",
      backgroundImage: "images/match/buttons/btn-done.png",
      top: 7,
      right: 8,
      width: 60,
      height: 30
    });
    this.doneButtonClick = function() {
      var leagueMatch;
      leagueMatch = null;
      showIndicator("Loading...");
      DataService.setupLocalDatabase();
      if (me.matchSetupEmailText.value !== "") {
        DataService.email = me.matchSetupEmailText.value;
      }
      if (me.nineBallTypeButtonActive.visible === true) {
        if (me.matchSetupTeamOneNumberText.value === "") {
          leagueMatch = new NineBallLeagueMatch("123", "456", "HomeTeam", "AwayTeam", "1:00 am", "Coin-Operated");
          leagueMatch.setMatchOne(new NineBallMatch("Isaac Wooten", "James Armstead", 1, 3, "123456", "234567", "123", "456"));
          leagueMatch.setMatchTwo(new NineBallMatch("Dude 1", "Chick 1", 2, 3, "123456", "234567", "123", "456"));
          leagueMatch.setMatchThree(new NineBallMatch("Dude 2", "Chick 2", 1, 2, "234567", "123456", "123", "456"));
          leagueMatch.setMatchFour(new NineBallMatch("Dude 3", "Chick 3", 1, 2, "123456", "234567", "123", "456"));
          leagueMatch.setMatchFive(new NineBallMatch("Dude 4", "Chick 4", 1, 1, "234567", "123456", "123", "456"));
        } else {
          leagueMatch = new NineBallLeagueMatch(me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value, "HomeTeam", "AwayTeam", "1:00 am", "Coin-Operated");
          leagueMatch.setMatchOne(new NineBallMatch(me.matchSetupTeamOnePlayerOneNameText.value, me.matchSetupTeamTwoPlayerOneNameText.value, parseInt(me.matchSetupTeamOnePlayerOneRankText.value), parseInt(me.matchSetupTeamTwoPlayerOneRankText.value), me.matchSetupTeamOnePlayerOneNumberText.value, me.matchSetupTeamTwoPlayerOneNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchTwo(new NineBallMatch(me.matchSetupTeamOnePlayerTwoNameText.value, me.matchSetupTeamTwoPlayerTwoNameText.value, parseInt(me.matchSetupTeamOnePlayerTwoRankText.value), parseInt(me.matchSetupTeamTwoPlayerTwoRankText.value), me.matchSetupTeamOnePlayerTwoNumberText.value, me.matchSetupTeamTwoPlayerTwoNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchThree(new NineBallMatch(me.matchSetupTeamOnePlayerThreeNameText.value, me.matchSetupTeamTwoPlayerThreeNameText.value, parseInt(me.matchSetupTeamOnePlayerThreeRankText.value), parseInt(me.matchSetupTeamTwoPlayerThreeRankText.value), me.matchSetupTeamOnePlayerThreeNumberText.value, me.matchSetupTeamTwoPlayerThreeNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchFour(new NineBallMatch(me.matchSetupTeamOnePlayerFourNameText.value, me.matchSetupTeamTwoPlayerFourNameText.value, parseInt(me.matchSetupTeamOnePlayerFourRankText.value), parseInt(me.matchSetupTeamTwoPlayerFourRankText.value), me.matchSetupTeamOnePlayerFourNumberText.value, me.matchSetupTeamTwoPlayerFourNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchFive(new NineBallMatch(me.matchSetupTeamOnePlayerFiveNameText.value, me.matchSetupTeamTwoPlayerFiveNameText.value, parseInt(me.matchSetupTeamOnePlayerFiveRankText.value), parseInt(me.matchSetupTeamTwoPlayerFiveRankText.value), me.matchSetupTeamOnePlayerFiveNumberText.value, me.matchSetupTeamTwoPlayerFiveNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
        }
      } else {
        if (me.matchSetupTeamOneNumberText.value === "") {
          leagueMatch = new EightBallLeagueMatch("123", "345", "HomeTeam", "AwayTeam", "1:00 am", "Coin-Operated");
          leagueMatch.setMatchOne(new EightBallMatch("Isaac Wooten", "James Armstead", 2, 3, "1", "2", "123", "345"));
          leagueMatch.setMatchTwo(new EightBallMatch("Dude 1", "Chick 1", 2, 3, "3", "4", "123", "345"));
          leagueMatch.setMatchThree(new EightBallMatch("Dude 2", "Chick 2", 2, 2, "5", "6", "123", "345"));
          leagueMatch.setMatchFour(new EightBallMatch("Dude 3", "Chick 3", 2, 2, "7", "8", "123", "345"));
          leagueMatch.setMatchFive(new EightBallMatch("Dude 4", "Chick 4", 2, 2, "9", "10", "123", "345"));
        } else {
          leagueMatch = new EightBallLeagueMatch(me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value, "HomeTeam", "AwayTeam", "1:00 am", "Coin-Operated");
          leagueMatch.setMatchOne(new EightBallMatch(me.matchSetupTeamOnePlayerOneNameText.value, me.matchSetupTeamTwoPlayerOneNameText.value, parseInt(me.matchSetupTeamOnePlayerOneRankText.value), parseInt(me.matchSetupTeamTwoPlayerOneRankText.value), me.matchSetupTeamOnePlayerOneNumberText.value, me.matchSetupTeamTwoPlayerOneNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchTwo(new EightBallMatch(me.matchSetupTeamOnePlayerTwoNameText.value, me.matchSetupTeamTwoPlayerTwoNameText.value, parseInt(me.matchSetupTeamOnePlayerTwoRankText.value), parseInt(me.matchSetupTeamTwoPlayerTwoRankText.value), me.matchSetupTeamOnePlayerTwoNumberText.value, me.matchSetupTeamTwoPlayerTwoNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchThree(new EightBallMatch(me.matchSetupTeamOnePlayerThreeNameText.value, me.matchSetupTeamTwoPlayerThreeNameText.value, parseInt(me.matchSetupTeamOnePlayerThreeRankText.value), parseInt(me.matchSetupTeamTwoPlayerThreeRankText.value), me.matchSetupTeamOnePlayerThreeNumberText.value, me.matchSetupTeamTwoPlayerThreeNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchFour(new EightBallMatch(me.matchSetupTeamOnePlayerFourNameText.value, me.matchSetupTeamTwoPlayerFourNameText.value, parseInt(me.matchSetupTeamOnePlayerFourRankText.value), parseInt(me.matchSetupTeamTwoPlayerFourRankText.value), me.matchSetupTeamOnePlayerFourNumberText.value, me.matchSetupTeamTwoPlayerFourNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
          leagueMatch.setMatchFive(new EightBallMatch(me.matchSetupTeamOnePlayerFiveNameText.value, me.matchSetupTeamTwoPlayerFiveNameText.value, parseInt(me.matchSetupTeamOnePlayerFiveRankText.value), parseInt(me.matchSetupTeamTwoPlayerFiveRankText.value), me.matchSetupTeamOnePlayerFiveNumberText.value, me.matchSetupTeamTwoPlayerFiveNumberText.value, me.matchSetupTeamOneNumberText.value, me.matchSetupTeamTwoNumberText.value));
        }
      }
      return play(leagueMatch);
    };
    this.matchSetupDoneButton.addEventListener("click", this.doneButtonClick);
    this.matchSetupTitleBar.add(this.matchSetupDoneButton);
    this.matchSetupTitleBar.add(this.playLabel);
    this.matchSetupTitleBar.add(this.dashboardButton);
    this.matchSetupFooter = Ti.UI.createView({
      backgroundColor: "transparent",
      backgroundImage: "images/match/layout/bg-tabmenu.png",
      bottom: 0,
      width: this.getPlatformWidth(),
      height: 49
    });
    this.selectedButtonBackground = Ti.UI.createView({
      backgroundImage: "images/match/buttons/btn-tabmenu-active.png",
      top: 3,
      left: 2,
      width: 73,
      height: 44
    });
    this.playButton = Ti.UI.createView({
      backgroundColor: "transparent",
      top: 3,
      left: 2,
      width: 73,
      height: 44
    });
    this.playButtonIcon = Ti.UI.createView({
      backgroundColor: "transparent",
      backgroundImage: "images/match/icons/icon-tabmenu-play-active.png",
      top: 8,
      left: 20,
      width: 32,
      height: 21
    });
    this.playButtonLabel = Ti.UI.createLabel({
      text: "Play",
      color: "#ffffff",
      shadowColor: "#000000",
      width: 73,
      bottom: 1,
      textAlign: "center",
      font: {
        fontSize: 9,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.playButton.add(this.playButtonIcon);
    this.playButton.add(this.playButtonLabel);
    this.matchSetupFooter.add(this.selectedButtonBackground);
    this.matchSetupFooter.add(this.playButton);
    this.matchSetupWindow.add(this.matchSetupFooter);
    this.matchSetupContainer = Ti.UI.createView({
      backgroundImage: (Ti.Platform.name !== "android" ? "images/match/layout/bg-menus-iphone.png" : "images/match/layout/bg-menus-android.png"),
      backgroundColor: "transparent",
      top: 44,
      left: 0,
      height: this.getPlatformHeight() - 95,
      width: this.getPlatformWidth()
    });
    this.matchSetupView = Ti.UI.createScrollView({
      contentWidth: "auto",
      contentHeight: "auto",
      backgroundColor: "transparent",
      top: 12,
      left: 12,
      height: 340,
      width: 295,
      showPagingControl: true
    });
    this.gameTypeLabel = Ti.UI.createLabel({
      text: "Select Game Type",
      color: "#ffffff",
      height: 40,
      width: 295,
      top: 0,
      textAlign: "center",
      font: {
        fontSize: 20,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchTypeContainer = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-dashboard-buttons-listview.png",
      backgroundColor: "transparent",
      top: 40,
      left: 16,
      height: 145,
      width: 262
    });
    this.eightBallTypeButton = Ti.UI.createImageView({
      backgroundImage: "images/match/layout/bg_play_gamebutton.png",
      backgroundColor: "transparent",
      top: 9,
      left: 5,
      height: 126,
      width: 124
    });
    this.eightBallTypeButtonActive = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg_play_gamebutton_active.png",
      backgroundColor: "transparent",
      top: 9,
      left: 5,
      height: 126,
      width: 124
    });
    this.eightBallTypeButtonActive.visible = false;
    this.eightBallTypeButtonIcon = Ti.UI.createImageView({
      backgroundImage: "images/match/icons/icon_gamebutton_8ball.png",
      backgroundColor: "transparent",
      top: 16,
      left: 21,
      height: 88,
      width: 88
    });
    this.eightBallTypeButtonLabel = Ti.UI.createLabel({
      text: "8-Ball",
      backgroundColor: "transparent",
      top: 94,
      left: 3,
      height: 25,
      width: 124,
      textAlign: "center",
      color: "#ffffff",
      font: {
        fontSize: 20,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchTypeContainer.add(this.eightBallTypeButtonActive);
    this.matchTypeContainer.add(this.eightBallTypeButton);
    this.matchTypeContainer.add(this.eightBallTypeButtonIcon);
    this.matchTypeContainer.add(this.eightBallTypeButtonLabel);
    this.nineBallTypeButton = Ti.UI.createImageView({
      backgroundImage: "images/match/layout/bg_play_gamebutton.png",
      backgroundColor: "transparent",
      top: 9,
      left: 132,
      height: 126,
      width: 124
    });
    this.nineBallTypeButton.visible = false;
    this.nineBallTypeButtonActive = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg_play_gamebutton_active.png",
      backgroundColor: "transparent",
      top: 9,
      left: 132,
      height: 126,
      width: 124
    });
    this.nineBallTypeButtonActive.visible = true;
    this.nineBallTypeButtonIcon = Ti.UI.createView({
      backgroundImage: "images/match/icons/icon_gamebutton_9ball.png",
      backgroundColor: "transparent",
      top: 16,
      left: 152,
      height: 88,
      width: 88
    });
    this.nineBallTypeButtonLabel = Ti.UI.createLabel({
      text: "9-Ball",
      backgroundColor: "transparent",
      top: 96,
      left: 134,
      height: 25,
      width: 124,
      color: "#ffffff",
      textAlign: "center",
      font: {
        fontSize: 20,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchTypeContainer.add(this.nineBallTypeButtonActive);
    this.matchTypeContainer.add(this.nineBallTypeButton);
    this.matchTypeContainer.add(this.nineBallTypeButtonIcon);
    this.matchTypeContainer.add(this.nineBallTypeButtonLabel);
    this.eightBallTypeClick = function() {
      if (me.eightBallTypeButtonActive.visible === false) {
        me.eightBallTypeButtonActive.visible = true;
        me.eightBallTypeButton.visible = false;
        me.nineBallTypeButtonActive.visible = false;
        return me.nineBallTypeButton.visible = true;
      }
    };
    this.nineBallTypeClick = function() {
      if (me.nineBallTypeButtonActive.visible === false) {
        me.eightBallTypeButtonActive.visible = false;
        me.eightBallTypeButton.visible = true;
        me.nineBallTypeButtonActive.visible = true;
        return me.nineBallTypeButton.visible = false;
      }
    };
    this.eightBallTypeButtonIcon.addEventListener("click", this.eightBallTypeClick);
    this.eightBallTypeButton.addEventListener("click", this.eightBallTypeClick);
    this.nineBallTypeButton.addEventListener("click", this.nineBallTypeClick);
    this.nineBallTypeButtonIcon.addEventListener("click", this.nineBallTypeClick);
    this.matchSetupTableExtender = Ti.UI.createView({
      backgroundColor: "transparent",
      top: 192,
      left: 18,
      height: 1452,
      width: 262
    });
    this.matchSetupTable = Ti.UI.createView({
      backgroundColor: "transparent",
      top: 0,
      left: 0,
      height: 1399,
      width: 262
    });
    this.matchSetupTableContainer = Ti.UI.createView({
      backgroundColor: "#0e1115",
      top: 7,
      left: 0,
      height: 1385,
      width: 262
    });
    this.matchSetupTableContainerTop = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg_menu_container_top.png",
      top: 0,
      left: 0,
      height: 7,
      width: 262
    });
    this.matchSetupTableContainerBottom = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg_menu_container_bottom.png",
      bottom: 0,
      left: 0,
      height: 7,
      width: 262
    });
    this.matchSetupTable.add(this.matchSetupTableContainerBottom);
    this.matchSetupTable.add(this.matchSetupTableContainerTop);
    this.matchSetupTable.add(this.matchSetupTableContainer);
    this.matchSetupTableExtender.add(this.matchSetupTable);
    this.matchSetupEmail = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 3,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupEmailLabel = Ti.UI.createLabel({
      text: "E-mail",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupEmailText = Ti.UI.createTextField({
      hintText: "i.wooten@gmail.com",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupEmail.add(this.matchSetupEmailLabel);
    this.matchSetupEmail.add(this.matchSetupEmailText);
    this.matchSetupTableExtender.add(this.matchSetupEmail);
    this.matchSetupTeamOneNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 48,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOneNumberLabel = Ti.UI.createLabel({
      text: "T1 Number",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOneNumberText = Ti.UI.createTextField({
      hintText: "Team One Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOneNumber.add(this.matchSetupTeamOneNumberLabel);
    this.matchSetupTeamOneNumber.add(this.matchSetupTeamOneNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOneNumber);
    this.matchSetupTeamTwoNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 93,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoNumberLabel = Ti.UI.createLabel({
      text: "T2 Number",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoNumberText = Ti.UI.createTextField({
      hintText: "Team Two Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoNumber.add(this.matchSetupTeamTwoNumberLabel);
    this.matchSetupTeamTwoNumber.add(this.matchSetupTeamTwoNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoNumber);
    this.matchSetupTeamOnePlayerOneName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 138,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerOneNameLabel = Ti.UI.createLabel({
      text: "T1 P1 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerOneNameText = Ti.UI.createTextField({
      hintText: "Player One Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerOneName.add(this.matchSetupTeamOnePlayerOneNameLabel);
    this.matchSetupTeamOnePlayerOneName.add(this.matchSetupTeamOnePlayerOneNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerOneName);
    this.matchSetupTeamOnePlayerOneNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 183,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerOneNumberLabel = Ti.UI.createLabel({
      text: "T1 P1 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerOneNumberText = Ti.UI.createTextField({
      hintText: "Player One Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerOneNumber.add(this.matchSetupTeamOnePlayerOneNumberLabel);
    this.matchSetupTeamOnePlayerOneNumber.add(this.matchSetupTeamOnePlayerOneNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerOneNumber);
    this.matchSetupTeamOnePlayerOneRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 228,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerOneRankLabel = Ti.UI.createLabel({
      text: "T1 P1 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerOneRankText = Ti.UI.createTextField({
      hintText: "Player One Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerOneRank.add(this.matchSetupTeamOnePlayerOneRankLabel);
    this.matchSetupTeamOnePlayerOneRank.add(this.matchSetupTeamOnePlayerOneRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerOneRank);
    this.matchSetupTeamTwoPlayerOneName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 273,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerOneNameLabel = Ti.UI.createLabel({
      text: "T2 P1 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerOneNameText = Ti.UI.createTextField({
      hintText: "Player One Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerOneName.add(this.matchSetupTeamTwoPlayerOneNameLabel);
    this.matchSetupTeamTwoPlayerOneName.add(this.matchSetupTeamTwoPlayerOneNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerOneName);
    this.matchSetupTeamTwoPlayerOneNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 318,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerOneNumberLabel = Ti.UI.createLabel({
      text: "T2 P1 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerOneNumberText = Ti.UI.createTextField({
      hintText: "Player One Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerOneNumber.add(this.matchSetupTeamTwoPlayerOneNumberLabel);
    this.matchSetupTeamTwoPlayerOneNumber.add(this.matchSetupTeamTwoPlayerOneNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerOneNumber);
    this.matchSetupTeamTwoPlayerOneRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 363,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerOneRankLabel = Ti.UI.createLabel({
      text: "T2 P1 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerOneRankText = Ti.UI.createTextField({
      hintText: "Player One Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerOneRank.add(this.matchSetupTeamTwoPlayerOneRankLabel);
    this.matchSetupTeamTwoPlayerOneRank.add(this.matchSetupTeamTwoPlayerOneRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerOneRank);
    this.matchSetupTeamOnePlayerTwoName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 408,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerTwoNameLabel = Ti.UI.createLabel({
      text: "T1 P2 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerTwoNameText = Ti.UI.createTextField({
      hintText: "Player Two Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerTwoName.add(this.matchSetupTeamOnePlayerTwoNameLabel);
    this.matchSetupTeamOnePlayerTwoName.add(this.matchSetupTeamOnePlayerTwoNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerTwoName);
    this.matchSetupTeamOnePlayerTwoNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 453,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerTwoNumberLabel = Ti.UI.createLabel({
      text: "T1 P2 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerTwoNumberText = Ti.UI.createTextField({
      hintText: "Player Two Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerTwoNumber.add(this.matchSetupTeamOnePlayerTwoNumberLabel);
    this.matchSetupTeamOnePlayerTwoNumber.add(this.matchSetupTeamOnePlayerTwoNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerTwoNumber);
    this.matchSetupTeamOnePlayerTwoRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 498,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerTwoRankLabel = Ti.UI.createLabel({
      text: "T1 P2 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerTwoRankText = Ti.UI.createTextField({
      hintText: "Player Two Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerTwoRank.add(this.matchSetupTeamOnePlayerTwoRankLabel);
    this.matchSetupTeamOnePlayerTwoRank.add(this.matchSetupTeamOnePlayerTwoRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerTwoRank);
    this.matchSetupTeamTwoPlayerTwoName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 543,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerTwoNameLabel = Ti.UI.createLabel({
      text: "T2 P2 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerTwoNameText = Ti.UI.createTextField({
      hintText: "Player Two Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerTwoName.add(this.matchSetupTeamTwoPlayerTwoNameLabel);
    this.matchSetupTeamTwoPlayerTwoName.add(this.matchSetupTeamTwoPlayerTwoNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerTwoName);
    this.matchSetupTeamTwoPlayerTwoNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 588,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerTwoNumberLabel = Ti.UI.createLabel({
      text: "T2 P2 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerTwoNumberText = Ti.UI.createTextField({
      hintText: "Player Two Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerTwoNumber.add(this.matchSetupTeamTwoPlayerTwoNumberLabel);
    this.matchSetupTeamTwoPlayerTwoNumber.add(this.matchSetupTeamTwoPlayerTwoNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerTwoNumber);
    this.matchSetupTeamTwoPlayerTwoRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 633,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerTwoRankLabel = Ti.UI.createLabel({
      text: "T2 P2 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerTwoRankText = Ti.UI.createTextField({
      hintText: "Player Two Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerTwoRank.add(this.matchSetupTeamTwoPlayerTwoRankLabel);
    this.matchSetupTeamTwoPlayerTwoRank.add(this.matchSetupTeamTwoPlayerTwoRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerTwoRank);
    this.matchSetupTeamOnePlayerThreeName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 678,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerThreeNameLabel = Ti.UI.createLabel({
      text: "T1 P3 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerThreeNameText = Ti.UI.createTextField({
      hintText: "Player Three Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerThreeName.add(this.matchSetupTeamOnePlayerThreeNameLabel);
    this.matchSetupTeamOnePlayerThreeName.add(this.matchSetupTeamOnePlayerThreeNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerThreeName);
    this.matchSetupTeamOnePlayerThreeNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 723,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerThreeNumberLabel = Ti.UI.createLabel({
      text: "T1 P3 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerThreeNumberText = Ti.UI.createTextField({
      hintText: "Player Three Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerThreeNumber.add(this.matchSetupTeamOnePlayerThreeNumberLabel);
    this.matchSetupTeamOnePlayerThreeNumber.add(this.matchSetupTeamOnePlayerThreeNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerThreeNumber);
    this.matchSetupTeamOnePlayerThreeRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 768,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerThreeRankLabel = Ti.UI.createLabel({
      text: "T1 P3 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerThreeRankText = Ti.UI.createTextField({
      hintText: "Player Three Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerThreeRank.add(this.matchSetupTeamOnePlayerThreeRankLabel);
    this.matchSetupTeamOnePlayerThreeRank.add(this.matchSetupTeamOnePlayerThreeRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerThreeRank);
    this.matchSetupTeamTwoPlayerThreeName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 813,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerThreeNameLabel = Ti.UI.createLabel({
      text: "T2 P3 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerThreeNameText = Ti.UI.createTextField({
      hintText: "Player Three Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerThreeName.add(this.matchSetupTeamTwoPlayerThreeNameLabel);
    this.matchSetupTeamTwoPlayerThreeName.add(this.matchSetupTeamTwoPlayerThreeNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerThreeName);
    this.matchSetupTeamTwoPlayerThreeNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 858,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerThreeNumberLabel = Ti.UI.createLabel({
      text: "T2 P3 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerThreeNumberText = Ti.UI.createTextField({
      hintText: "Player Three Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerThreeNumber.add(this.matchSetupTeamTwoPlayerThreeNumberLabel);
    this.matchSetupTeamTwoPlayerThreeNumber.add(this.matchSetupTeamTwoPlayerThreeNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerThreeNumber);
    this.matchSetupTeamTwoPlayerThreeRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 903,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerThreeRankLabel = Ti.UI.createLabel({
      text: "T2 P3 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerThreeRankText = Ti.UI.createTextField({
      hintText: "Player Three Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerThreeRank.add(this.matchSetupTeamTwoPlayerThreeRankLabel);
    this.matchSetupTeamTwoPlayerThreeRank.add(this.matchSetupTeamTwoPlayerThreeRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerThreeRank);
    this.matchSetupTeamOnePlayerFourName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 948,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerFourNameLabel = Ti.UI.createLabel({
      text: "T1 P4 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFourNameText = Ti.UI.createTextField({
      hintText: "Player Four Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFourName.add(this.matchSetupTeamOnePlayerFourNameLabel);
    this.matchSetupTeamOnePlayerFourName.add(this.matchSetupTeamOnePlayerFourNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerFourName);
    this.matchSetupTeamOnePlayerFourNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 993,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerFourNumberLabel = Ti.UI.createLabel({
      text: "T1 P4 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFourNumberText = Ti.UI.createTextField({
      hintText: "Player Four Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFourNumber.add(this.matchSetupTeamOnePlayerFourNumberLabel);
    this.matchSetupTeamOnePlayerFourNumber.add(this.matchSetupTeamOnePlayerFourNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerFourNumber);
    this.matchSetupTeamOnePlayerFourRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1038,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerFourRankLabel = Ti.UI.createLabel({
      text: "T1 P4 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFourRankText = Ti.UI.createTextField({
      hintText: "Player Four Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFourRank.add(this.matchSetupTeamOnePlayerFourRankLabel);
    this.matchSetupTeamOnePlayerFourRank.add(this.matchSetupTeamOnePlayerFourRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerFourRank);
    this.matchSetupTeamTwoPlayerFourName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1083,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerFourNameLabel = Ti.UI.createLabel({
      text: "T2 P4 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFourNameText = Ti.UI.createTextField({
      hintText: "Player Four Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFourName.add(this.matchSetupTeamTwoPlayerFourNameLabel);
    this.matchSetupTeamTwoPlayerFourName.add(this.matchSetupTeamTwoPlayerFourNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerFourName);
    this.matchSetupTeamTwoPlayerFourNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1128,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerFourNumberLabel = Ti.UI.createLabel({
      text: "T2 P4 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFourNumberText = Ti.UI.createTextField({
      hintText: "Player Four Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFourNumber.add(this.matchSetupTeamTwoPlayerFourNumberLabel);
    this.matchSetupTeamTwoPlayerFourNumber.add(this.matchSetupTeamTwoPlayerFourNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerFourNumber);
    this.matchSetupTeamTwoPlayerFourRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1173,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerFourRankLabel = Ti.UI.createLabel({
      text: "T2 P4 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFourRankText = Ti.UI.createTextField({
      hintText: "Player Four Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFourRank.add(this.matchSetupTeamTwoPlayerFourRankLabel);
    this.matchSetupTeamTwoPlayerFourRank.add(this.matchSetupTeamTwoPlayerFourRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerFourRank);
    this.matchSetupTeamOnePlayerFiveName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1218,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerFiveNameLabel = Ti.UI.createLabel({
      text: "T1 P5 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFiveNameText = Ti.UI.createTextField({
      hintText: "Player Five Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFiveName.add(this.matchSetupTeamOnePlayerFiveNameLabel);
    this.matchSetupTeamOnePlayerFiveName.add(this.matchSetupTeamOnePlayerFiveNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerFiveName);
    this.matchSetupTeamOnePlayerFiveNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1263,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerFiveNumberLabel = Ti.UI.createLabel({
      text: "T1 P5 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFiveNumberText = Ti.UI.createTextField({
      hintText: "Player Five Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFiveNumber.add(this.matchSetupTeamOnePlayerFiveNumberLabel);
    this.matchSetupTeamOnePlayerFiveNumber.add(this.matchSetupTeamOnePlayerFiveNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerFiveNumber);
    this.matchSetupTeamOnePlayerFiveRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1308,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamOnePlayerFiveRankLabel = Ti.UI.createLabel({
      text: "T1 P5 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFiveRankText = Ti.UI.createTextField({
      hintText: "Player Five Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamOnePlayerFiveRank.add(this.matchSetupTeamOnePlayerFiveRankLabel);
    this.matchSetupTeamOnePlayerFiveRank.add(this.matchSetupTeamOnePlayerFiveRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamOnePlayerFiveRank);
    this.matchSetupTeamTwoPlayerFiveName = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1353,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerFiveNameLabel = Ti.UI.createLabel({
      text: "T2 P5 Name",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFiveNameText = Ti.UI.createTextField({
      hintText: "Player Five Name",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFiveName.add(this.matchSetupTeamTwoPlayerFiveNameLabel);
    this.matchSetupTeamTwoPlayerFiveName.add(this.matchSetupTeamTwoPlayerFiveNameText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerFiveName);
    this.matchSetupTeamTwoPlayerFiveNumber = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1398,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerFiveNumberLabel = Ti.UI.createLabel({
      text: "T2 P5 Num",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFiveNumberText = Ti.UI.createTextField({
      hintText: "Player Five Number",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFiveNumber.add(this.matchSetupTeamTwoPlayerFiveNumberLabel);
    this.matchSetupTeamTwoPlayerFiveNumber.add(this.matchSetupTeamTwoPlayerFiveNumberText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerFiveNumber);
    this.matchSetupTeamTwoPlayerFiveRank = Ti.UI.createView({
      backgroundImage: "images/match/layout/bg-demosetup-field.png",
      top: 1443,
      left: 2,
      height: 42,
      width: 258
    });
    this.matchSetupTeamTwoPlayerFiveRankLabel = Ti.UI.createLabel({
      text: "T2 P5 Rank",
      color: "#ffff00",
      top: 12,
      left: 6,
      height: 20,
      width: 100,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFiveRankText = Ti.UI.createTextField({
      hintText: "Player Five Rank",
      backgroundColor: "#ffffff",
      top: 12,
      left: 110,
      height: 20,
      width: 130,
      suppressReturn: true,
      font: {
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "HelveticaNeue-Bold"
      }
    });
    this.matchSetupTeamTwoPlayerFiveRank.add(this.matchSetupTeamTwoPlayerFiveRankLabel);
    this.matchSetupTeamTwoPlayerFiveRank.add(this.matchSetupTeamTwoPlayerFiveRankText);
    this.matchSetupTableExtender.add(this.matchSetupTeamTwoPlayerFiveRank);
    this.matchSetupView.add(this.matchSetupTableExtender);
    this.matchSetupView.add(this.gameTypeLabel);
    this.matchSetupView.add(this.matchTypeContainer);
    this.matchSetupContainer.add(this.matchSetupView);
    this.matchSetupWindow.add(this.matchSetupTitleBar);
    this.matchSetupWindow.add(this.matchSetupContainer);
    this.showMatchSetup = function() {
      if (Ti.Platform.name !== "android") {
        Ti.UI.iPhone.showStatusBar();
        return this.matchSetupWindow.open({
          fullscreen: false
        });
      } else {
        return this.matchSetupWindow.open({
          fullscreen: true
        });
      }
    };
    showMatchSetup();
    return this;
  };

  indWin = null;

  actInd = null;

}).call(this);
