// Generated by CoffeeScript 1.3.1
(function() {
  var PracticeMatch,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  PracticeMatch = (function(_super) {

    __extends(PracticeMatch, _super);

    PracticeMatch.name = 'PracticeMatch';

    function PracticeMatch() {
      return PracticeMatch.__super__.constructor.apply(this, arguments);
    }

    PracticeMatch.prototype.defaults = {};

    PracticeMatch.prototype.initialize = function() {
      return console.log(this);
    };

    return PracticeMatch;

  })($CS.Models.Match.Type);

  $CS.Models.Match.Type.PracticeMatch = PracticeMatch;

}).call(this);
