// Generated by CoffeeScript 1.3.3
(function() {
  var GridView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  GridView = (function(_super) {

    __extends(GridView, _super);

    GridView.prototype.defaults = {};

    function GridView() {
      var activityIcon, activityIconBackground, activityIconContainer, activityIconLabel, activityWindowHolder, eventsIcon, eventsIconBackground, eventsIconContainer, eventsIconLabel, eventsWindowHolder, liveIcon, liveIconBackground, liveIconContainer, liveIconLabel, liveWindowHolder, newsIcon, newsIconBackground, newsIconContainer, newsIconLabel, newsWindowHolder, playIcon, playIconBackground, playIconContainer, playIconLabel, playWindowHolder, profileIcon, profileIconBackground, profileIconContainer, profileIconLabel, profileWindowHolder, rulesIcon, rulesIconBackground, rulesIconContainer, rulesIconLabel, rulesWindowHolder, settingsIcon, settingsIconBackground, settingsIconContainer, settingsIconLabel, settingsWindowHolder, teamsIcon, teamsIconBackground, teamsIconContainer, teamsIconLabel, teamsWindowHolder;
      _.extend(this, this.defaults);
      playWindowHolder = null;
      teamsWindowHolder = null;
      activityWindowHolder = null;
      profileWindowHolder = null;
      newsWindowHolder = null;
      eventsWindowHolder = null;
      liveWindowHolder = null;
      rulesWindowHolder = null;
      settingsWindowHolder = null;
      this.gridView = Ti.UI.createView({
        top: 12,
        left: 12,
        height: 390,
        width: 295,
        isNinePatch: false
      });
      playIconContainer = Ti.UI.createView({
        left: 13,
        top: 16,
        height: 102,
        width: 82
      });
      playIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      playIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-play-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      playIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Play",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      playIcon.addEventListener("click", function() {
        if (playWindowHolder == null) {
          playWindowHolder = matchSetup();
        } else {
          playWindowHolder.showMatchSetup();
        }
        return dashboardWindow.hide();
      });
      playIconBackground.add(playIcon);
      playIconContainer.add(playIconBackground);
      playIconContainer.add(playIconLabel);
      teamsIconContainer = Ti.UI.createView({
        left: 108,
        top: 16,
        height: 102,
        width: 82
      });
      teamsIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      teamsIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-leagues-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      teamsIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Teams",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      teamsIcon.addEventListener("click", function() {
        if (teamsWindowHolder == null) {
          teamsWindowHolder = teams();
        } else {
          teamsWindowHolder.showTeams();
        }
        return dashboardWindow.hide();
      });
      teamsIconBackground.add(teamsIcon);
      teamsIconContainer.add(teamsIconBackground);
      teamsIconContainer.add(teamsIconLabel);
      activityIconContainer = Ti.UI.createView({
        left: 203,
        top: 16,
        height: 102,
        width: 82
      });
      activityIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      activityIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-activity-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      activityIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Activity",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      activityIcon.addEventListener("click", function() {
        if (activityWindowHolder == null) {
          activityWindowHolder = activity();
        } else {
          activityWindowHolder.showActivity();
        }
        return dashboardWindow.hide();
      });
      activityIconBackground.add(activityIcon);
      activityIconContainer.add(activityIconBackground);
      activityIconContainer.add(activityIconLabel);
      profileIconContainer = Ti.UI.createView({
        left: 13,
        top: 137,
        height: 102,
        width: 82
      });
      profileIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      profileIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-profile-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      profileIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Profile",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      profileIcon.addEventListener("click", function() {
        if (profileWindowHolder == null) {
          profileWindowHolder = profile();
        } else {
          profileWindowHolder.showProfile();
        }
        return dashboardWindow.hide();
      });
      profileIconBackground.add(profileIcon);
      profileIconContainer.add(profileIconBackground);
      profileIconContainer.add(profileIconLabel);
      newsIconContainer = Ti.UI.createView({
        left: 108,
        top: 137,
        height: 102,
        width: 82
      });
      newsIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      newsIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-news-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      newsIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "News",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      newsIcon.addEventListener("click", function() {
        if (newsWindowHolder == null) {
          newsWindowHolder = news();
        } else {
          newsWindowHolder.showNews();
        }
        return dashboardWindow.hide();
      });
      newsIconBackground.add(newsIcon);
      newsIconContainer.add(newsIconBackground);
      newsIconContainer.add(newsIconLabel);
      eventsIconContainer = Ti.UI.createView({
        left: 203,
        top: 137,
        height: 102,
        width: 82
      });
      eventsIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      eventsIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-events-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      eventsIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Events",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      eventsIcon.addEventListener("click", function() {
        if (eventsWindowHolder == null) {
          eventsWindowHolder = events();
        } else {
          eventsWindowHolder.showEvents();
        }
        return dashboardWindow.hide();
      });
      eventsIconBackground.add(eventsIcon);
      eventsIconContainer.add(eventsIconBackground);
      eventsIconContainer.add(eventsIconLabel);
      liveIconContainer = Ti.UI.createView({
        left: 13,
        top: 255,
        height: 102,
        width: 82
      });
      liveIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      liveIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-live-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      liveIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Live",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      liveIcon.addEventListener("click", function() {
        if (liveWindowHolder == null) {
          liveWindowHolder = live();
        } else {
          liveWindowHolder.showLive();
        }
        return dashboardWindow.hide();
      });
      liveIconBackground.add(liveIcon);
      liveIconContainer.add(liveIconBackground);
      liveIconContainer.add(liveIconLabel);
      rulesIconContainer = Ti.UI.createView({
        left: 108,
        top: 255,
        height: 102,
        width: 82
      });
      rulesIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      rulesIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-rules-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      rulesIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Rules",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      rulesIcon.addEventListener("click", function() {
        if (rulesWindowHolder == null) {
          rulesWindowHolder = rules();
        } else {
          rulesWindowHolder.showRules();
        }
        return dashboardWindow.hide();
      });
      rulesIconBackground.add(rulesIcon);
      rulesIconContainer.add(rulesIconBackground);
      rulesIconContainer.add(rulesIconLabel);
      settingsIconContainer = Ti.UI.createView({
        left: 203,
        top: 255,
        height: 102,
        width: 82
      });
      settingsIconBackground = Ti.UI.createView({
        backgroundImage: "images/match/layout/bg-dashboard-buttons-gridview.png",
        top: 0,
        left: 0,
        height: 83,
        width: 82
      });
      settingsIcon = Ti.UI.createView({
        backgroundImage: "images/match/buttons/btn-dashboard-settings-large.png",
        top: 5,
        left: 6,
        height: 71,
        width: 70
      });
      settingsIconLabel = Ti.UI.createLabel({
        color: "#ffffff",
        backgroundColor: "transparent",
        text: "Settings",
        top: 80,
        height: 20,
        width: 82,
        textAlign: "center",
        font: {
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      settingsIcon.addEventListener("click", function() {
        if (settingsWindowHolder == null) {
          settingsWindowHolder = settings();
        } else {
          settingsWindowHolder.showSettings();
        }
        return dashboardWindow.hide();
      });
      settingsIconBackground.add(settingsIcon);
      settingsIconContainer.add(settingsIconBackground);
      settingsIconContainer.add(settingsIconLabel);
      this.gridView.add(playIconContainer);
      this.gridView.add(teamsIconContainer);
      this.gridView.add(activityIconContainer);
      this.gridView.add(profileIconContainer);
      this.gridView.add(newsIconContainer);
      this.gridView.add(eventsIconContainer);
      this.gridView.add(liveIconContainer);
      this.gridView.add(rulesIconContainer);
      this.gridView.add(settingsIconContainer);
    }

    return GridView;

  })($CS.Views.Dashboard);

  $CS.Views.Dashboard.GridView = GridView;

}).call(this);
