// Generated by CoffeeScript 1.3.3
(function() {
  var RulesView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RulesView = (function(_super) {

    __extends(RulesView, _super);

    RulesView.prototype.defaults = {};

    function RulesView() {
      _.extend(this, this.defaults);
      this.setUp();
    }

    RulesView.prototype.setUp = function() {
      var toolbarLabel,
        _this = this;
      this.rulesWindow = Ti.UI.createWindow({
        orientationModes: [Ti.UI.PORTRAIT]
      });
      this.rulesContainer = Ti.UI.createView({
        backgroundColor: "#000000",
        top: 0,
        left: 0,
        height: this.getPlatformHeight(),
        width: this.getPlatformWidth()
      });
      this.rulesScrollView = Ti.UI.createScrollView({
        contentWidth: "auto",
        contentHeight: "auto",
        minZoomScale: 0,
        maxZoomScale: 10,
        backgroundColor: "transparent",
        top: 12,
        left: 12,
        height: 390,
        width: 295,
        showPagingControl: true
      });
      this.rulesView = Ti.UI.createView({
        height: 243,
        width: 243,
        font: {
          fontSize: 13,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      this.comingSoon = Ti.UI.createView({
        backgroundImage: "images/match/layout/overlay-comingsoon.png",
        backgroundColor: "transparent",
        top: 20,
        height: 243,
        width: 243
      });
      this.rulesLabel = Ti.UI.createLabel({
        text: "test test test test ",
        top: 0,
        left: 0,
        color: "#ffffff",
        height: 1500,
        width: 285,
        font: {
          fontSize: 13,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      this.rulesView.add(this.comingSoon);
      toolbarLabel = Ti.UI.createLabel({
        text: "Rules",
        color: "#ffffff",
        shadowColor: "#000000",
        textAlign: "center",
        font: {
          fontSize: 20,
          fontWeight: "bold",
          fontFamily: "HelveticaNeue-Bold"
        }
      });
      titleBar.add(dashboardButton);
      titleBar.add(toolbarLabel);
      this.rulesContainer.add(toolsMenuContainer);
      this.rulesContainer.add(titleBar);
      this.rulesContainer.add(this.rulesView);
      this.rulesWindow.add(this.rulesContainer);
      this.dashboardButton.addEventListener("click", function() {
        this.rulesWindow.close();
        return this.dashboardWindow.show();
      });
      ({
        showRules: function() {
          if (Ti.Platform.name !== "android") {
            Ti.UI.iPhone.showStatusBar();
            return _this.rulesWindow.open({
              fullscreen: false
            });
          } else {
            return _this.rulesWindow.open({
              fullscreen: true
            });
          }
        }
      });
      return showRules();
    };

    return RulesView;

  })($CS.Views.Dashboard);

  $CS.Views.Dashboard.RulesView = RulesView;

}).call(this);
