// Generated by CoffeeScript 1.3.3
(function() {
  var MixedDoubles,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MixedDoubles = (function(_super) {

    __extends(MixedDoubles, _super);

    function MixedDoubles() {
      return MixedDoubles.__super__.constructor.apply(this, arguments);
    }

    MixedDoubles.prototype.defaults = {};

    MixedDoubles.prototype.initialize = function(options) {
      if (options == null) {
        options = {};
      }
      return _.extend(this, this.defaults);
    };

    return MixedDoubles;

  })($CS.Models.League);

  $CS.Models.League.MixedDoubles = MixedDoubles;

}).call(this);
